// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: frontend.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{0}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*PluginEndpoint      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetEndpoints() []*PluginEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_frontend_proto protoreflect.FileDescriptor

const file_frontend_proto_rawDesc = "" +
	"\n" +
	"\x0efrontend.proto\x12\bfrontend\x1a\fplugin.proto\"\r\n" +
	"\vListRequest\"D\n" +
	"\fListResponse\x124\n" +
	"\tendpoints\x18\x01 \x03(\v2\x16.plugin.PluginEndpointR\tendpoints2\x90\x01\n" +
	"\x0eAdapterService\x125\n" +
	"\x04List\x12\x15.frontend.ListRequest\x1a\x16.frontend.ListResponse\x12G\n" +
	"\x04Call\x12\x1e.plugin.EndpointRequestMessage\x1a\x1f.plugin.EndpointResponseMessageB,Z*github.com/bgrewell/dtac-agent/api/grpc/gob\x06proto3"

var (
	file_frontend_proto_rawDescOnce sync.Once
	file_frontend_proto_rawDescData []byte
)

func file_frontend_proto_rawDescGZIP() []byte {
	file_frontend_proto_rawDescOnce.Do(func() {
		file_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)))
	})
	return file_frontend_proto_rawDescData
}

var file_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_frontend_proto_goTypes = []any{
	(*ListRequest)(nil),             // 0: frontend.ListRequest
	(*ListResponse)(nil),            // 1: frontend.ListResponse
	(*PluginEndpoint)(nil),          // 2: plugin.PluginEndpoint
	(*EndpointRequestMessage)(nil),  // 3: plugin.EndpointRequestMessage
	(*EndpointResponseMessage)(nil), // 4: plugin.EndpointResponseMessage
}
var file_frontend_proto_depIdxs = []int32{
	2, // 0: frontend.ListResponse.endpoints:type_name -> plugin.PluginEndpoint
	0, // 1: frontend.AdapterService.List:input_type -> frontend.ListRequest
	3, // 2: frontend.AdapterService.Call:input_type -> plugin.EndpointRequestMessage
	1, // 3: frontend.AdapterService.List:output_type -> frontend.ListResponse
	4, // 4: frontend.AdapterService.Call:output_type -> plugin.EndpointResponseMessage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_frontend_proto_init() }
func file_frontend_proto_init() {
	if File_frontend_proto != nil {
		return
	}
	file_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_proto_goTypes,
		DependencyIndexes: file_frontend_proto_depIdxs,
		MessageInfos:      file_frontend_proto_msgTypes,
	}.Build()
	File_frontend_proto = out.File
	file_frontend_proto_goTypes = nil
	file_frontend_proto_depIdxs = nil
}
