// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: module.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModuleRegisterRequest contains the configuration and metadata for module registration
type ModuleRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Config contains module-specific configuration as JSON
	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// DefaultSecure indicates if endpoints should be secure by default
	DefaultSecure bool `protobuf:"varint,2,opt,name=default_secure,json=defaultSecure,proto3" json:"default_secure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRegisterRequest) Reset() {
	*x = ModuleRegisterRequest{}
	mi := &file_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRegisterRequest) ProtoMessage() {}

func (x *ModuleRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRegisterRequest.ProtoReflect.Descriptor instead.
func (*ModuleRegisterRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRegisterRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *ModuleRegisterRequest) GetDefaultSecure() bool {
	if x != nil {
		return x.DefaultSecure
	}
	return false
}

// ModuleRegisterResponse contains module registration details
type ModuleRegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ModuleType indicates the type of module (e.g., "web", "daemon")
	ModuleType string `protobuf:"bytes,1,opt,name=module_type,json=moduleType,proto3" json:"module_type,omitempty"`
	// Capabilities lists what the module supports (e.g., "static_files", "proxy", "api")
	Capabilities  []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleRegisterResponse) Reset() {
	*x = ModuleRegisterResponse{}
	mi := &file_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRegisterResponse) ProtoMessage() {}

func (x *ModuleRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRegisterResponse.ProtoReflect.Descriptor instead.
func (*ModuleRegisterResponse) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleRegisterResponse) GetModuleType() string {
	if x != nil {
		return x.ModuleType
	}
	return ""
}

func (x *ModuleRegisterResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// TokenRequest is used by modules to request JWT tokens from DTAC
type TokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scopes are the requested permissions/scopes for the token
	Scopes []string `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// ExpiresIn is the requested token lifetime in seconds (agent may override)
	ExpiresIn     int64 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{2}
}

func (x *TokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenRequest) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// TokenRefreshRequest is used to refresh an existing token
type TokenRefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RefreshToken is the refresh token to exchange for a new access token
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRefreshRequest) Reset() {
	*x = TokenRefreshRequest{}
	mi := &file_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRefreshRequest) ProtoMessage() {}

func (x *TokenRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRefreshRequest.ProtoReflect.Descriptor instead.
func (*TokenRefreshRequest) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// TokenResponse contains the issued JWT token
type TokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AccessToken is the JWT access token
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// RefreshToken is the refresh token (if applicable)
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// ExpiresIn is the token lifetime in seconds
	ExpiresIn int64 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// TokenType is typically "Bearer"
	TokenType     string `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_module_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

var File_module_proto protoreflect.FileDescriptor

const file_module_proto_rawDesc = "" +
	"\n" +
	"\fmodule.proto\x12\x06module\x1a\fplugin.proto\"V\n" +
	"\x15ModuleRegisterRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12%\n" +
	"\x0edefault_secure\x18\x02 \x01(\bR\rdefaultSecure\"]\n" +
	"\x16ModuleRegisterResponse\x12\x1f\n" +
	"\vmodule_type\x18\x01 \x01(\tR\n" +
	"moduleType\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"E\n" +
	"\fTokenRequest\x12\x16\n" +
	"\x06scopes\x18\x01 \x03(\tR\x06scopes\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\":\n" +
	"\x13TokenRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x95\x01\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType2\x97\x02\n" +
	"\rModuleService\x12I\n" +
	"\bRegister\x12\x1d.module.ModuleRegisterRequest\x1a\x1e.module.ModuleRegisterResponse\x12:\n" +
	"\rLoggingStream\x12\x13.plugin.LoggingArgs\x1a\x12.plugin.LogMessage0\x01\x12;\n" +
	"\fRequestToken\x12\x14.module.TokenRequest\x1a\x15.module.TokenResponse\x12B\n" +
	"\fRefreshToken\x12\x1b.module.TokenRefreshRequest\x1a\x15.module.TokenResponseB,Z*github.com/bgrewell/dtac-agent/api/grpc/gob\x06proto3"

var (
	file_module_proto_rawDescOnce sync.Once
	file_module_proto_rawDescData []byte
)

func file_module_proto_rawDescGZIP() []byte {
	file_module_proto_rawDescOnce.Do(func() {
		file_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)))
	})
	return file_module_proto_rawDescData
}

var file_module_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_module_proto_goTypes = []any{
	(*ModuleRegisterRequest)(nil),  // 0: module.ModuleRegisterRequest
	(*ModuleRegisterResponse)(nil), // 1: module.ModuleRegisterResponse
	(*TokenRequest)(nil),           // 2: module.TokenRequest
	(*TokenRefreshRequest)(nil),    // 3: module.TokenRefreshRequest
	(*TokenResponse)(nil),          // 4: module.TokenResponse
	(*LoggingArgs)(nil),            // 5: plugin.LoggingArgs
	(*LogMessage)(nil),             // 6: plugin.LogMessage
}
var file_module_proto_depIdxs = []int32{
	0, // 0: module.ModuleService.Register:input_type -> module.ModuleRegisterRequest
	5, // 1: module.ModuleService.LoggingStream:input_type -> plugin.LoggingArgs
	2, // 2: module.ModuleService.RequestToken:input_type -> module.TokenRequest
	3, // 3: module.ModuleService.RefreshToken:input_type -> module.TokenRefreshRequest
	1, // 4: module.ModuleService.Register:output_type -> module.ModuleRegisterResponse
	6, // 5: module.ModuleService.LoggingStream:output_type -> plugin.LogMessage
	4, // 6: module.ModuleService.RequestToken:output_type -> module.TokenResponse
	4, // 7: module.ModuleService.RefreshToken:output_type -> module.TokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_module_proto_init() }
func file_module_proto_init() {
	if File_module_proto != nil {
		return
	}
	file_plugin_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_proto_rawDesc), len(file_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_module_proto_goTypes,
		DependencyIndexes: file_module_proto_depIdxs,
		MessageInfos:      file_module_proto_msgTypes,
	}.Build()
	File_module_proto = out.File
	file_module_proto_goTypes = nil
	file_module_proto_depIdxs = nil
}
