// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: plugin.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define log level as an enum for clarity and type safety
type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
	LogLevel_FATAL   LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
		4: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"DEBUG":   0,
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
		"FATAL":   4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// EndpointRequestMessage represents a gRPC message for a request made to an endpoint.
// It encapsulates the method being called and the necessary request data.
type EndpointRequestMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Method is the name of the method or action being invoked on the endpoint.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Request captures all the inputs that are available to be sent to the endpoint.
	Request       *EndpointRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRequestMessage) Reset() {
	*x = EndpointRequestMessage{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRequestMessage) ProtoMessage() {}

func (x *EndpointRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRequestMessage.ProtoReflect.Descriptor instead.
func (*EndpointRequestMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointRequestMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointRequestMessage) GetRequest() *EndpointRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// EndpointResponseMessage represents a gRPC message for a response returned from an endpoint.
// It contains the response data and any error that might have occurred during processing.
type EndpointResponseMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is a unique identifier for the response, typically used for correlating requests and responses.
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Response captures all the output that is returned from the endpoint.
	Response *EndpointResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	// Error is a string representing any error that might have occurred during the endpoint's processing.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointResponseMessage) Reset() {
	*x = EndpointResponseMessage{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResponseMessage) ProtoMessage() {}

func (x *EndpointResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResponseMessage.ProtoReflect.Descriptor instead.
func (*EndpointResponseMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointResponseMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EndpointResponseMessage) GetResponse() *EndpointResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *EndpointResponseMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// EndpointRequest represents the data structure for a request made to an endpoint in the framework.
type EndpointRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata holds additional data relevant to the processing of the request.
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Headers represent HTTP-style headers accompanying the request.
	Headers map[string]*StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parameters are query or path parameters used by the endpoint to process the request.
	Parameters map[string]*StringList `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Body holds the raw data of the request in binary format.
	Body          []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRequest) Reset() {
	*x = EndpointRequest{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRequest) ProtoMessage() {}

func (x *EndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRequest.ProtoReflect.Descriptor instead.
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EndpointRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EndpointRequest) GetParameters() map[string]*StringList {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *EndpointRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// EndpointResponse represents the data structure for the response returned from an endpoint.
type EndpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata holds additional data about the response.
	Metadata map[string]string `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Headers represent HTTP-style headers accompanying the response.
	Headers map[string]*StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Parameters may include additional data returned from the endpoint.
	Parameters map[string]*StringList `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Value is the primary data of the response in binary format.
	Value         []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointResponse) Reset() {
	*x = EndpointResponse{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResponse) ProtoMessage() {}

func (x *EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResponse.ProtoReflect.Descriptor instead.
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EndpointResponse) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *EndpointResponse) GetParameters() map[string]*StringList {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *EndpointResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// StringList is a message type that encapsulates a list of strings.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        string                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	DefaultSecure bool                   `protobuf:"varint,2,opt,name=default_secure,json=defaultSecure,proto3" json:"default_secure,omitempty"`
	// BrokerAddress is the address of the agent's broker service for plugin-to-plugin communication
	// Format: "host:port"
	BrokerAddress string `protobuf:"bytes,3,opt,name=broker_address,json=brokerAddress,proto3" json:"broker_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *RegisterRequest) GetDefaultSecure() bool {
	if x != nil {
		return x.DefaultSecure
	}
	return false
}

func (x *RegisterRequest) GetBrokerAddress() string {
	if x != nil {
		return x.BrokerAddress
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*PluginEndpoint      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetEndpoints() []*PluginEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// PluginEndpoint represents a configuration for an API endpoint in a plugin.
type PluginEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path specifies the endpoint's unique path or identifier.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Action represents the type of operation this endpoint performs.
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// Description is a human-readable description of the endpoint.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Secure indicates whether this endpoint requires authentication and authorization.
	Secure bool `protobuf:"varint,4,opt,name=secure,proto3" json:"secure,omitempty"`
	// AuthGroup specifies the minimum authorization group required to access this endpoint.
	AuthGroup string `protobuf:"bytes,5,opt,name=auth_group,json=authGroup,proto3" json:"auth_group,omitempty"`
	// ExpectedMetadataSchema defines the JSON Schema for the expected metadata structure in the request.
	ExpectedMetadataSchema string `protobuf:"bytes,6,opt,name=expected_metadata_schema,json=expectedMetadataSchema,proto3" json:"expected_metadata_schema,omitempty"`
	// ExpectedHeadersSchema defines the JSON Schema for the expected headers structure in the request.
	ExpectedHeadersSchema string `protobuf:"bytes,7,opt,name=expected_headers_schema,json=expectedHeadersSchema,proto3" json:"expected_headers_schema,omitempty"`
	// ExpectedParametersSchema defines the JSON Schema for the expected parameters structure in the request.
	ExpectedParametersSchema string `protobuf:"bytes,8,opt,name=expected_parameters_schema,json=expectedParametersSchema,proto3" json:"expected_parameters_schema,omitempty"`
	// ExpectedBodySchema defines the JSON Schema for the expected body structure in the request.
	ExpectedBodySchema string `protobuf:"bytes,9,opt,name=expected_body_schema,json=expectedBodySchema,proto3" json:"expected_body_schema,omitempty"`
	// ExpectedOutputSchema defines the JSON Schema for the expected output structure in the response.
	ExpectedOutputSchema string `protobuf:"bytes,10,opt,name=expected_output_schema,json=expectedOutputSchema,proto3" json:"expected_output_schema,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PluginEndpoint) Reset() {
	*x = PluginEndpoint{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEndpoint) ProtoMessage() {}

func (x *PluginEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEndpoint.ProtoReflect.Descriptor instead.
func (*PluginEndpoint) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PluginEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PluginEndpoint) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginEndpoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginEndpoint) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *PluginEndpoint) GetAuthGroup() string {
	if x != nil {
		return x.AuthGroup
	}
	return ""
}

func (x *PluginEndpoint) GetExpectedMetadataSchema() string {
	if x != nil {
		return x.ExpectedMetadataSchema
	}
	return ""
}

func (x *PluginEndpoint) GetExpectedHeadersSchema() string {
	if x != nil {
		return x.ExpectedHeadersSchema
	}
	return ""
}

func (x *PluginEndpoint) GetExpectedParametersSchema() string {
	if x != nil {
		return x.ExpectedParametersSchema
	}
	return ""
}

func (x *PluginEndpoint) GetExpectedBodySchema() string {
	if x != nil {
		return x.ExpectedBodySchema
	}
	return ""
}

func (x *PluginEndpoint) GetExpectedOutputSchema() string {
	if x != nil {
		return x.ExpectedOutputSchema
	}
	return ""
}

// Logging arguments which for now is empty
type LoggingArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingArgs) Reset() {
	*x = LoggingArgs{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingArgs) ProtoMessage() {}

func (x *LoggingArgs) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingArgs.ProtoReflect.Descriptor instead.
func (*LoggingArgs) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

// Key-value pair for structured data
type LogField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // You can define more types if needed (e.g., int, float, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogField) Reset() {
	*x = LogField{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogField) ProtoMessage() {}

func (x *LogField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogField.ProtoReflect.Descriptor instead.
func (*LogField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *LogField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Main log message structure
type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=plugin.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fields        []*LogField            `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"` // Structured data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogMessage) GetFields() []*LogField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// PluginCallRequest represents a request from one plugin to call another plugin
type PluginCallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TargetPlugin is the name of the plugin to call
	TargetPlugin string `protobuf:"bytes,1,opt,name=target_plugin,json=targetPlugin,proto3" json:"target_plugin,omitempty"`
	// Method is the endpoint method to call on the target plugin
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Action is the action type (Read, Write, Create, Delete)
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Request contains the request data to send to the target plugin
	Request       *EndpointRequest `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCallRequest) Reset() {
	*x = PluginCallRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCallRequest) ProtoMessage() {}

func (x *PluginCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCallRequest.ProtoReflect.Descriptor instead.
func (*PluginCallRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PluginCallRequest) GetTargetPlugin() string {
	if x != nil {
		return x.TargetPlugin
	}
	return ""
}

func (x *PluginCallRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PluginCallRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PluginCallRequest) GetRequest() *EndpointRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// PluginCallResponse represents the response from a plugin-to-plugin call
type PluginCallResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response contains the response data from the target plugin
	Response *EndpointResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	// Error contains any error message if the call failed
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginCallResponse) Reset() {
	*x = PluginCallResponse{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCallResponse) ProtoMessage() {}

func (x *PluginCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCallResponse.ProtoReflect.Descriptor instead.
func (*PluginCallResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PluginCallResponse) GetResponse() *EndpointResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PluginCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ListPluginsRequest is an empty request for listing plugins
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

// ListPluginsResponse contains the list of loaded plugins
type ListPluginsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PluginNames contains the names of all loaded plugins
	PluginNames   []string `protobuf:"bytes,1,rep,name=plugin_names,json=pluginNames,proto3" json:"plugin_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ListPluginsResponse) GetPluginNames() []string {
	if x != nil {
		return x.PluginNames
	}
	return nil
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x06plugin\"c\n" +
	"\x16EndpointRequestMessage\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x121\n" +
	"\arequest\x18\x02 \x01(\v2\x17.plugin.EndpointRequestR\arequest\"u\n" +
	"\x17EndpointResponseMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\bresponse\x18\x02 \x01(\v2\x18.plugin.EndpointResponseR\bresponse\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xd1\x03\n" +
	"\x0fEndpointRequest\x12A\n" +
	"\bmetadata\x18\x01 \x03(\v2%.plugin.EndpointRequest.MetadataEntryR\bmetadata\x12>\n" +
	"\aheaders\x18\x02 \x03(\v2$.plugin.EndpointRequest.HeadersEntryR\aheaders\x12G\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2'.plugin.EndpointRequest.ParametersEntryR\n" +
	"parameters\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.plugin.StringListR\x05value:\x028\x01\x1aQ\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.plugin.StringListR\x05value:\x028\x01\"\xd7\x03\n" +
	"\x10EndpointResponse\x12B\n" +
	"\bmetadata\x18\x01 \x03(\v2&.plugin.EndpointResponse.MetadataEntryR\bmetadata\x12?\n" +
	"\aheaders\x18\x02 \x03(\v2%.plugin.EndpointResponse.HeadersEntryR\aheaders\x12H\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2(.plugin.EndpointResponse.ParametersEntryR\n" +
	"parameters\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aN\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.plugin.StringListR\x05value:\x028\x01\x1aQ\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.plugin.StringListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"w\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12%\n" +
	"\x0edefault_secure\x18\x02 \x01(\bR\rdefaultSecure\x12%\n" +
	"\x0ebroker_address\x18\x03 \x01(\tR\rbrokerAddress\"H\n" +
	"\x10RegisterResponse\x124\n" +
	"\tendpoints\x18\x01 \x03(\v2\x16.plugin.PluginEndpointR\tendpoints\"\xad\x03\n" +
	"\x0ePluginEndpoint\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06secure\x18\x04 \x01(\bR\x06secure\x12\x1d\n" +
	"\n" +
	"auth_group\x18\x05 \x01(\tR\tauthGroup\x128\n" +
	"\x18expected_metadata_schema\x18\x06 \x01(\tR\x16expectedMetadataSchema\x126\n" +
	"\x17expected_headers_schema\x18\a \x01(\tR\x15expectedHeadersSchema\x12<\n" +
	"\x1aexpected_parameters_schema\x18\b \x01(\tR\x18expectedParametersSchema\x120\n" +
	"\x14expected_body_schema\x18\t \x01(\tR\x12expectedBodySchema\x124\n" +
	"\x16expected_output_schema\x18\n" +
	" \x01(\tR\x14expectedOutputSchema\"\r\n" +
	"\vLoggingArgs\"2\n" +
	"\bLogField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"x\n" +
	"\n" +
	"LogMessage\x12&\n" +
	"\x05level\x18\x01 \x01(\x0e2\x10.plugin.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x06fields\x18\x03 \x03(\v2\x10.plugin.LogFieldR\x06fields\"\x9b\x01\n" +
	"\x11PluginCallRequest\x12#\n" +
	"\rtarget_plugin\x18\x01 \x01(\tR\ftargetPlugin\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x121\n" +
	"\arequest\x18\x04 \x01(\v2\x17.plugin.EndpointRequestR\arequest\"`\n" +
	"\x12PluginCallResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.plugin.EndpointResponseR\bresponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12ListPluginsRequest\"8\n" +
	"\x13ListPluginsResponse\x12!\n" +
	"\fplugin_names\x18\x01 \x03(\tR\vpluginNames*B\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\t\n" +
	"\x05FATAL\x10\x042\xd3\x01\n" +
	"\rPluginService\x12=\n" +
	"\bRegister\x12\x17.plugin.RegisterRequest\x1a\x18.plugin.RegisterResponse\x12G\n" +
	"\x04Call\x12\x1e.plugin.EndpointRequestMessage\x1a\x1f.plugin.EndpointResponseMessage\x12:\n" +
	"\rLoggingStream\x12\x13.plugin.LoggingArgs\x1a\x12.plugin.LogMessage0\x012\x9b\x01\n" +
	"\fAgentService\x12C\n" +
	"\n" +
	"CallPlugin\x12\x19.plugin.PluginCallRequest\x1a\x1a.plugin.PluginCallResponse\x12F\n" +
	"\vListPlugins\x12\x1a.plugin.ListPluginsRequest\x1a\x1b.plugin.ListPluginsResponseB,Z*github.com/bgrewell/dtac-agent/api/grpc/gob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_plugin_proto_goTypes = []any{
	(LogLevel)(0),                   // 0: plugin.LogLevel
	(*EndpointRequestMessage)(nil),  // 1: plugin.EndpointRequestMessage
	(*EndpointResponseMessage)(nil), // 2: plugin.EndpointResponseMessage
	(*EndpointRequest)(nil),         // 3: plugin.EndpointRequest
	(*EndpointResponse)(nil),        // 4: plugin.EndpointResponse
	(*StringList)(nil),              // 5: plugin.StringList
	(*RegisterRequest)(nil),         // 6: plugin.RegisterRequest
	(*RegisterResponse)(nil),        // 7: plugin.RegisterResponse
	(*PluginEndpoint)(nil),          // 8: plugin.PluginEndpoint
	(*LoggingArgs)(nil),             // 9: plugin.LoggingArgs
	(*LogField)(nil),                // 10: plugin.LogField
	(*LogMessage)(nil),              // 11: plugin.LogMessage
	(*PluginCallRequest)(nil),       // 12: plugin.PluginCallRequest
	(*PluginCallResponse)(nil),      // 13: plugin.PluginCallResponse
	(*ListPluginsRequest)(nil),      // 14: plugin.ListPluginsRequest
	(*ListPluginsResponse)(nil),     // 15: plugin.ListPluginsResponse
	nil,                             // 16: plugin.EndpointRequest.MetadataEntry
	nil,                             // 17: plugin.EndpointRequest.HeadersEntry
	nil,                             // 18: plugin.EndpointRequest.ParametersEntry
	nil,                             // 19: plugin.EndpointResponse.MetadataEntry
	nil,                             // 20: plugin.EndpointResponse.HeadersEntry
	nil,                             // 21: plugin.EndpointResponse.ParametersEntry
}
var file_plugin_proto_depIdxs = []int32{
	3,  // 0: plugin.EndpointRequestMessage.request:type_name -> plugin.EndpointRequest
	4,  // 1: plugin.EndpointResponseMessage.response:type_name -> plugin.EndpointResponse
	16, // 2: plugin.EndpointRequest.metadata:type_name -> plugin.EndpointRequest.MetadataEntry
	17, // 3: plugin.EndpointRequest.headers:type_name -> plugin.EndpointRequest.HeadersEntry
	18, // 4: plugin.EndpointRequest.parameters:type_name -> plugin.EndpointRequest.ParametersEntry
	19, // 5: plugin.EndpointResponse.metadata:type_name -> plugin.EndpointResponse.MetadataEntry
	20, // 6: plugin.EndpointResponse.headers:type_name -> plugin.EndpointResponse.HeadersEntry
	21, // 7: plugin.EndpointResponse.parameters:type_name -> plugin.EndpointResponse.ParametersEntry
	8,  // 8: plugin.RegisterResponse.endpoints:type_name -> plugin.PluginEndpoint
	0,  // 9: plugin.LogMessage.level:type_name -> plugin.LogLevel
	10, // 10: plugin.LogMessage.fields:type_name -> plugin.LogField
	3,  // 11: plugin.PluginCallRequest.request:type_name -> plugin.EndpointRequest
	4,  // 12: plugin.PluginCallResponse.response:type_name -> plugin.EndpointResponse
	5,  // 13: plugin.EndpointRequest.HeadersEntry.value:type_name -> plugin.StringList
	5,  // 14: plugin.EndpointRequest.ParametersEntry.value:type_name -> plugin.StringList
	5,  // 15: plugin.EndpointResponse.HeadersEntry.value:type_name -> plugin.StringList
	5,  // 16: plugin.EndpointResponse.ParametersEntry.value:type_name -> plugin.StringList
	6,  // 17: plugin.PluginService.Register:input_type -> plugin.RegisterRequest
	1,  // 18: plugin.PluginService.Call:input_type -> plugin.EndpointRequestMessage
	9,  // 19: plugin.PluginService.LoggingStream:input_type -> plugin.LoggingArgs
	12, // 20: plugin.AgentService.CallPlugin:input_type -> plugin.PluginCallRequest
	14, // 21: plugin.AgentService.ListPlugins:input_type -> plugin.ListPluginsRequest
	7,  // 22: plugin.PluginService.Register:output_type -> plugin.RegisterResponse
	2,  // 23: plugin.PluginService.Call:output_type -> plugin.EndpointResponseMessage
	11, // 24: plugin.PluginService.LoggingStream:output_type -> plugin.LogMessage
	13, // 25: plugin.AgentService.CallPlugin:output_type -> plugin.PluginCallResponse
	15, // 26: plugin.AgentService.ListPlugins:output_type -> plugin.ListPluginsResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
