// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: plugin.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PluginService_Register_FullMethodName      = "/plugin.PluginService/Register"
	PluginService_Call_FullMethodName          = "/plugin.PluginService/Call"
	PluginService_LoggingStream_FullMethodName = "/plugin.PluginService/LoggingStream"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Call(ctx context.Context, in *EndpointRequestMessage, opts ...grpc.CallOption) (*EndpointResponseMessage, error)
	LoggingStream(ctx context.Context, in *LoggingArgs, opts ...grpc.CallOption) (PluginService_LoggingStreamClient, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PluginService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Call(ctx context.Context, in *EndpointRequestMessage, opts ...grpc.CallOption) (*EndpointResponseMessage, error) {
	out := new(EndpointResponseMessage)
	err := c.cc.Invoke(ctx, PluginService_Call_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) LoggingStream(ctx context.Context, in *LoggingArgs, opts ...grpc.CallOption) (PluginService_LoggingStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &PluginService_ServiceDesc.Streams[0], PluginService_LoggingStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginServiceLoggingStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PluginService_LoggingStreamClient interface {
	Recv() (*LogMessage, error)
	grpc.ClientStream
}

type pluginServiceLoggingStreamClient struct {
	grpc.ClientStream
}

func (x *pluginServiceLoggingStreamClient) Recv() (*LogMessage, error) {
	m := new(LogMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Call(context.Context, *EndpointRequestMessage) (*EndpointResponseMessage, error)
	LoggingStream(*LoggingArgs, PluginService_LoggingStreamServer) error
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginServiceServer) Call(context.Context, *EndpointRequestMessage) (*EndpointResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedPluginServiceServer) LoggingStream(*LoggingArgs, PluginService_LoggingStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method LoggingStream not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndpointRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Call(ctx, req.(*EndpointRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_LoggingStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PluginServiceServer).LoggingStream(m, &pluginServiceLoggingStreamServer{stream})
}

type PluginService_LoggingStreamServer interface {
	Send(*LogMessage) error
	grpc.ServerStream
}

type pluginServiceLoggingStreamServer struct {
	grpc.ServerStream
}

func (x *pluginServiceLoggingStreamServer) Send(m *LogMessage) error {
	return x.ServerStream.SendMsg(m)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PluginService_Register_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _PluginService_Call_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoggingStream",
			Handler:       _PluginService_LoggingStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
