// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.6.1
// source: plugin-api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_REQUEST_UNKNOWN   RequestType = 0
	RequestType_REQUEST_HEARTBEAT RequestType = 1
	RequestType_REQUEST_REGISTER  RequestType = 10
	RequestType_REQUEST_EXEC      RequestType = 20
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0:  "REQUEST_UNKNOWN",
		1:  "REQUEST_HEARTBEAT",
		10: "REQUEST_REGISTER",
		20: "REQUEST_EXEC",
	}
	RequestType_value = map[string]int32{
		"REQUEST_UNKNOWN":   0,
		"REQUEST_HEARTBEAT": 1,
		"REQUEST_REGISTER":  10,
		"REQUEST_EXEC":      20,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_api_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_plugin_api_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_api_proto_rawDescGZIP(), []int{0}
}

type PluginMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId   uint64      `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Title       string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RequestType RequestType `protobuf:"varint,10,opt,name=request_type,json=requestType,proto3,enum=systemapi_plugin.RequestType" json:"request_type,omitempty"`
	// Types that are assignable to RequestPayload:
	//	*PluginMessage_Heartbeat
	//	*PluginMessage_Register
	RequestPayload isPluginMessage_RequestPayload `protobuf_oneof:"request_payload"`
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_plugin_api_proto_rawDescGZIP(), []int{0}
}

func (x *PluginMessage) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *PluginMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PluginMessage) GetRequestType() RequestType {
	if x != nil {
		return x.RequestType
	}
	return RequestType_REQUEST_UNKNOWN
}

func (m *PluginMessage) GetRequestPayload() isPluginMessage_RequestPayload {
	if m != nil {
		return m.RequestPayload
	}
	return nil
}

func (x *PluginMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetRequestPayload().(*PluginMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *PluginMessage) GetRegister() *Register {
	if x, ok := x.GetRequestPayload().(*PluginMessage_Register); ok {
		return x.Register
	}
	return nil
}

type isPluginMessage_RequestPayload interface {
	isPluginMessage_RequestPayload()
}

type PluginMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,20,opt,name=heartbeat,proto3,oneof"`
}

type PluginMessage_Register struct {
	Register *Register `protobuf:"bytes,21,opt,name=register,proto3,oneof"`
}

func (*PluginMessage_Heartbeat) isPluginMessage_RequestPayload() {}

func (*PluginMessage_Register) isPluginMessage_RequestPayload() {}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeatId uint64 `protobuf:"varint,1,opt,name=beat_id,json=beatId,proto3" json:"beat_id,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_plugin_api_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetBeatId() uint64 {
	if x != nil {
		return x.BeatId
	}
	return 0
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginName string   `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	RouteBase  string   `protobuf:"bytes,10,opt,name=route_base,json=routeBase,proto3" json:"route_base,omitempty"`
	Routes     []string `protobuf:"bytes,11,rep,name=routes,proto3" json:"routes,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plugin_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_plugin_api_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *Register) GetRouteBase() string {
	if x != nil {
		return x.RouteBase
	}
	return ""
}

func (x *Register) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_plugin_api_proto protoreflect.FileDescriptor

var file_plugin_api_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x22, 0x90, 0x02, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a,
	0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x42, 0x11, 0x0a, 0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x24, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x65, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x65, 0x61, 0x74, 0x49, 0x64, 0x22, 0x62, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x2a, 0x61, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52,
	0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x45, 0x58,
	0x45, 0x43, 0x10, 0x14, 0x32, 0x62, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x58,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x12, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x1f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x47, 0x72, 0x65, 0x77, 0x65, 0x6c, 0x6c, 0x2f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plugin_api_proto_rawDescOnce sync.Once
	file_plugin_api_proto_rawDescData = file_plugin_api_proto_rawDesc
)

func file_plugin_api_proto_rawDescGZIP() []byte {
	file_plugin_api_proto_rawDescOnce.Do(func() {
		file_plugin_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_plugin_api_proto_rawDescData)
	})
	return file_plugin_api_proto_rawDescData
}

var file_plugin_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_api_proto_goTypes = []interface{}{
	(RequestType)(0),      // 0: systemapi_plugin.RequestType
	(*PluginMessage)(nil), // 1: systemapi_plugin.PluginMessage
	(*Heartbeat)(nil),     // 2: systemapi_plugin.Heartbeat
	(*Register)(nil),      // 3: systemapi_plugin.Register
}
var file_plugin_api_proto_depIdxs = []int32{
	0, // 0: systemapi_plugin.PluginMessage.request_type:type_name -> systemapi_plugin.RequestType
	2, // 1: systemapi_plugin.PluginMessage.heartbeat:type_name -> systemapi_plugin.Heartbeat
	3, // 2: systemapi_plugin.PluginMessage.register:type_name -> systemapi_plugin.Register
	1, // 3: systemapi_plugin.Plugin.ControlChannel:input_type -> systemapi_plugin.PluginMessage
	1, // 4: systemapi_plugin.Plugin.ControlChannel:output_type -> systemapi_plugin.PluginMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_api_proto_init() }
func file_plugin_api_proto_init() {
	if File_plugin_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plugin_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plugin_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_plugin_api_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PluginMessage_Heartbeat)(nil),
		(*PluginMessage_Register)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plugin_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_api_proto_goTypes,
		DependencyIndexes: file_plugin_api_proto_depIdxs,
		EnumInfos:         file_plugin_api_proto_enumTypes,
		MessageInfos:      file_plugin_api_proto_msgTypes,
	}.Build()
	File_plugin_api_proto = out.File
	file_plugin_api_proto_rawDesc = nil
	file_plugin_api_proto_goTypes = nil
	file_plugin_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PluginClient is the client API for Plugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PluginClient interface {
	ControlChannel(ctx context.Context, opts ...grpc.CallOption) (Plugin_ControlChannelClient, error)
}

type pluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginClient(cc grpc.ClientConnInterface) PluginClient {
	return &pluginClient{cc}
}

func (c *pluginClient) ControlChannel(ctx context.Context, opts ...grpc.CallOption) (Plugin_ControlChannelClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Plugin_serviceDesc.Streams[0], "/systemapi_plugin.Plugin/ControlChannel", opts...)
	if err != nil {
		return nil, err
	}
	x := &pluginControlChannelClient{stream}
	return x, nil
}

type Plugin_ControlChannelClient interface {
	Send(*PluginMessage) error
	Recv() (*PluginMessage, error)
	grpc.ClientStream
}

type pluginControlChannelClient struct {
	grpc.ClientStream
}

func (x *pluginControlChannelClient) Send(m *PluginMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pluginControlChannelClient) Recv() (*PluginMessage, error) {
	m := new(PluginMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PluginServer is the server API for Plugin service.
type PluginServer interface {
	ControlChannel(Plugin_ControlChannelServer) error
}

// UnimplementedPluginServer can be embedded to have forward compatible implementations.
type UnimplementedPluginServer struct {
}

func (*UnimplementedPluginServer) ControlChannel(Plugin_ControlChannelServer) error {
	return status.Errorf(codes.Unimplemented, "method ControlChannel not implemented")
}

func RegisterPluginServer(s *grpc.Server, srv PluginServer) {
	s.RegisterService(&_Plugin_serviceDesc, srv)
}

func _Plugin_ControlChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginServer).ControlChannel(&pluginControlChannelServer{stream})
}

type Plugin_ControlChannelServer interface {
	Send(*PluginMessage) error
	Recv() (*PluginMessage, error)
	grpc.ServerStream
}

type pluginControlChannelServer struct {
	grpc.ServerStream
}

func (x *pluginControlChannelServer) Send(m *PluginMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pluginControlChannelServer) Recv() (*PluginMessage, error) {
	m := new(PluginMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Plugin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "systemapi_plugin.Plugin",
	HandlerType: (*PluginServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ControlChannel",
			Handler:       _Plugin_ControlChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin-api.proto",
}
