package structs

import (
	"encoding/json"
	"testing"
)

var (
	input = `{
        "interface_set": [
            {
                "params": {},
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Connection X722 for 10GBASE-T",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [
                    {
                        "id": 7987,
                        "mode": "static",
                        "ip_address": "10.21.26.1",
                        "subnet": {
                            "name": "10.21.24.0/21",
                            "description": "",
                            "vlan": {
                                "vid": 0,
                                "mtu": 1500,
                                "dhcp_on": true,
                                "external_dhcp": null,
                                "relay_vlan": null,
                                "id": 5001,
                                "primary_rack": "xnesx3",
                                "space": "undefined",
                                "fabric": "fabric-bm",
                                "fabric_id": 0,
                                "secondary_rack": null,
                                "name": "untagged",
                                "resource_uri": "/MAAS/api/2.0/vlans/5001/"
                            },
                            "cidr": "10.21.24.0/21",
                            "rdns_mode": 2,
                            "gateway_ip": "10.21.24.1",
                            "dns_servers": [
                                "10.21.0.2"
                            ],
                            "allow_dns": true,
                            "allow_proxy": true,
                            "active_discovery": false,
                            "managed": true,
                            "disabled_boot_architectures": [],
                            "id": 1,
                            "space": "undefined",
                            "resource_uri": "/MAAS/api/2.0/subnets/1/"
                        }
                    }
                ],
                "sriov_max_vf": 32,
                "effective_mtu": 1500,
                "name": "eth.t.bm",
                "numa_node": 0,
                "mac_address": "a4:bf:01:57:5d:c2",
                "id": 72,
                "link_connected": true,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 1000,
                "interface_speed": 10000,
                "vlan": {
                    "vid": 0,
                    "mtu": 1500,
                    "dhcp_on": true,
                    "external_dhcp": null,
                    "relay_vlan": null,
                    "id": 5001,
                    "primary_rack": "xnesx3",
                    "space": "undefined",
                    "fabric": "fabric-bm",
                    "fabric_id": 0,
                    "secondary_rack": null,
                    "name": "untagged",
                    "resource_uri": "/MAAS/api/2.0/vlans/5001/"
                },
                "firmware_version": "5.30 0x80002a31 1.2926.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/72/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Connection X722 for 10GBASE-T",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 32,
                "effective_mtu": 1500,
                "name": "eno2",
                "numa_node": 0,
                "mac_address": "a4:bf:01:57:5d:c3",
                "id": 113,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 10000,
                "vlan": null,
                "firmware_version": "5.30 0x80002a31 1.2926.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/113/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens785f0",
                "numa_node": 0,
                "mac_address": "3c:fd:fe:c4:53:88",
                "id": 114,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/114/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens785f1",
                "numa_node": 0,
                "mac_address": "3c:fd:fe:c4:53:89",
                "id": 115,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/115/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens786f0",
                "numa_node": 0,
                "mac_address": "3c:fd:fe:c4:52:7c",
                "id": 116,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/116/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens786f1",
                "numa_node": 0,
                "mac_address": "3c:fd:fe:c4:52:7d",
                "id": 117,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/117/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens787f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:78",
                "id": 118,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/118/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens787f1",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:79",
                "id": 119,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/119/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens801f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:52:f0",
                "id": 120,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/120/"
            },
            {
                "params": {},
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [
                    {
                        "id": 7988,
                        "mode": "link_up"
                    }
                ],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "eth.t.core",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:52:f1",
                "id": 121,
                "link_connected": true,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 25000,
                "interface_speed": 25000,
                "vlan": {
                    "vid": 0,
                    "mtu": 1500,
                    "dhcp_on": false,
                    "external_dhcp": null,
                    "relay_vlan": null,
                    "id": 5004,
                    "primary_rack": null,
                    "space": "undefined",
                    "fabric": "fabric-data",
                    "fabric_id": 3,
                    "secondary_rack": null,
                    "name": "untagged",
                    "resource_uri": "/MAAS/api/2.0/vlans/5004/"
                },
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/121/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens802f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:51:1c",
                "id": 122,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/122/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens802f1",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:51:1d",
                "id": 123,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/123/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens803f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:e4",
                "id": 124,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/124/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens803f1",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:e5",
                "id": 125,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/125/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens817f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:98",
                "id": 126,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/126/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens817f1",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:99",
                "id": 127,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/127/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens818f0",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:d4",
                "id": 128,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/128/"
            },
            {
                "params": "",
                "vendor": "Intel Corporation",
                "parents": [],
                "product": "Ethernet Controller XXV710 for 25GbE SFP28",
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "sriov"
                ],
                "links": [],
                "sriov_max_vf": 64,
                "effective_mtu": 1500,
                "name": "ens818f1",
                "numa_node": 1,
                "mac_address": "3c:fd:fe:c4:53:d5",
                "id": 129,
                "link_connected": false,
                "enabled": true,
                "discovered": null,
                "children": [],
                "link_speed": 0,
                "interface_speed": 25000,
                "vlan": null,
                "firmware_version": "9.00 0x8000ce7c 1.3179.0",
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/129/"
            }
        ],
        "status": 6,
        "cpu_count": 80,
        "memory": 196608,
        "commissioning_status_name": "Passed",
        "default_gateways": {
            "ipv4": {
                "gateway_ip": "10.21.24.1",
                "link_id": null
            },
            "ipv6": {
                "gateway_ip": null,
                "link_id": null
            }
        },
        "cpu_speed": 2400,
        "bios_boot_method": "uefi",
        "power_type": "ipmi",
        "cpu_test_status": -1,
        "address_ttl": null,
        "hwe_kernel": "ga-22.04",
        "status_action": "",
        "testing_status": 2,
        "hardware_info": {
            "system_vendor": "Intel Corporation",
            "system_product": "S2600WFT",
            "system_family": "Family",
            "system_version": "R2308WFTZS",
            "system_sku": "SKU Number",
            "system_serial": "BQWT83000150",
            "cpu_model": "Intel(R) Xeon(R) Gold 6148 CPU",
            "mainboard_vendor": "Intel Corporation",
            "mainboard_product": "S2600WFT",
            "mainboard_serial": "BQWF82500607",
            "mainboard_version": "H48104-862",
            "mainboard_firmware_vendor": "Intel Corporation",
            "mainboard_firmware_date": "03/21/2022",
            "mainboard_firmware_version": "SE5C620.86B.02.01.0015.032120220358",
            "chassis_vendor": "...............................",
            "chassis_type": "Rack Mount Chassis",
            "chassis_serial": "..................",
            "chassis_version": ".................."
        },
        "boot_interface": {
            "params": {},
            "vendor": "Intel Corporation",
            "parents": [],
            "product": "Ethernet Connection X722 for 10GBASE-T",
            "type": "physical",
            "system_id": "xca83r",
            "tags": [
                "sriov"
            ],
            "links": [
                {
                    "id": 7987,
                    "mode": "static",
                    "ip_address": "10.21.26.1",
                    "subnet": {
                        "name": "10.21.24.0/21",
                        "description": "",
                        "vlan": {
                            "vid": 0,
                            "mtu": 1500,
                            "dhcp_on": true,
                            "external_dhcp": null,
                            "relay_vlan": null,
                            "id": 5001,
                            "primary_rack": "xnesx3",
                            "space": "undefined",
                            "fabric": "fabric-bm",
                            "fabric_id": 0,
                            "secondary_rack": null,
                            "name": "untagged",
                            "resource_uri": "/MAAS/api/2.0/vlans/5001/"
                        },
                        "cidr": "10.21.24.0/21",
                        "rdns_mode": 2,
                        "gateway_ip": "10.21.24.1",
                        "dns_servers": [
                            "10.21.0.2"
                        ],
                        "allow_dns": true,
                        "allow_proxy": true,
                        "active_discovery": false,
                        "managed": true,
                        "disabled_boot_architectures": [],
                        "id": 1,
                        "space": "undefined",
                        "resource_uri": "/MAAS/api/2.0/subnets/1/"
                    }
                }
            ],
            "sriov_max_vf": 32,
            "effective_mtu": 1500,
            "name": "eth.t.bm",
            "numa_node": 0,
            "mac_address": "a4:bf:01:57:5d:c2",
            "id": 72,
            "link_connected": true,
            "enabled": true,
            "discovered": null,
            "children": [],
            "link_speed": 1000,
            "interface_speed": 10000,
            "vlan": {
                "vid": 0,
                "mtu": 1500,
                "dhcp_on": true,
                "external_dhcp": null,
                "relay_vlan": null,
                "id": 5001,
                "primary_rack": "xnesx3",
                "space": "undefined",
                "fabric": "fabric-bm",
                "fabric_id": 0,
                "secondary_rack": null,
                "name": "untagged",
                "resource_uri": "/MAAS/api/2.0/vlans/5001/"
            },
            "firmware_version": "5.30 0x80002a31 1.2926.0",
            "resource_uri": "/MAAS/api/2.0/nodes/xca83r/interfaces/72/"
        },
        "system_id": "xca83r",
        "zone": {
            "name": "default",
            "description": "",
            "id": 1,
            "resource_uri": "/MAAS/api/2.0/zones/default/"
        },
        "blockdevice_set": [
            {
                "firmware_version": "0100",
                "uuid": null,
                "path": "/dev/disk/by-dname/sda",
                "serial": "BTYF832007GQ480BGN",
                "size": 480103981056,
                "partition_table_type": "GPT",
                "block_size": 4096,
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "ssd"
                ],
                "used_for": "GPT partitioned with 2 partitions",
                "storage_pool": null,
                "name": "sda",
                "numa_node": 0,
                "id_path": "/dev/disk/by-id/wwn-0x55cd2e414fd81ab5",
                "id": 36,
                "model": "INTEL SSDSC2KB48",
                "filesystem": null,
                "partitions": [
                    {
                        "uuid": "55f46dc8-c0b1-402b-a189-8a527c335bbc",
                        "size": 536870912,
                        "bootable": true,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sda-part1",
                        "used_for": "fat32 formatted filesystem mounted at /boot/efi",
                        "device_id": 36,
                        "id": 88,
                        "filesystem": {
                            "fstype": "fat32",
                            "label": "efi",
                            "uuid": "e720f90b-ed63-4e7e-9a31-d5a265481205",
                            "mount_point": "/boot/efi",
                            "mount_options": null
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/88"
                    },
                    {
                        "uuid": "97c411c5-03d8-4c84-9ed8-ae415b5599db",
                        "size": 479559942144,
                        "bootable": false,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sda-part2",
                        "used_for": "LVM volume for vgroot",
                        "device_id": 36,
                        "id": 89,
                        "filesystem": {
                            "fstype": "lvm-pv",
                            "label": null,
                            "uuid": "b080d210-ca82-478d-8fea-22c3548aa2a5",
                            "mount_point": null,
                            "mount_options": null
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/89"
                    }
                ],
                "used_size": 480102055936,
                "available_size": 0,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/"
            },
            {
                "firmware_version": "CC26",
                "uuid": null,
                "path": "/dev/disk/by-dname/sdb",
                "serial": "Z4ZAYHSC",
                "size": 2000398934016,
                "partition_table_type": "GPT",
                "block_size": 4096,
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "rotary",
                    "1rpm"
                ],
                "used_for": "GPT partitioned with 1 partition",
                "storage_pool": null,
                "name": "sdb",
                "numa_node": 0,
                "id_path": "/dev/disk/by-id/wwn-0x5000c500b0b65305",
                "id": 37,
                "model": "ST2000DM006-2DM1",
                "filesystem": null,
                "partitions": [
                    {
                        "uuid": "0a22bbfa-04a1-4b88-80f1-1519da666b16",
                        "size": 2000389406720,
                        "bootable": false,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sdb-part1",
                        "used_for": "btrfs formatted filesystem mounted at /var/lib/libvirt",
                        "device_id": 37,
                        "id": 92,
                        "filesystem": {
                            "fstype": "btrfs",
                            "label": "",
                            "uuid": "f98aeed2-16bf-4ccb-a1a4-fb2baf40cb3b",
                            "mount_point": "/var/lib/libvirt",
                            "mount_options": ""
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/37/partition/92"
                    }
                ],
                "used_size": 2000394649600,
                "available_size": 4194304,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/37/"
            },
            {
                "uuid": "24e02618-b16a-49a0-9bbf-86b6bbc890bc",
                "path": "/dev/disk/by-dname/vgroot-lvroot",
                "serial": null,
                "size": 479555747840,
                "partition_table_type": null,
                "block_size": 4096,
                "type": "virtual",
                "system_id": "xca83r",
                "tags": [],
                "used_for": "ext4 formatted filesystem mounted at /",
                "storage_pool": null,
                "name": "vgroot-lvroot",
                "numa_node": null,
                "id_path": null,
                "id": 101,
                "model": null,
                "filesystem": {
                    "fstype": "ext4",
                    "label": "root",
                    "uuid": "c08143d5-b9c9-4853-9113-cb10ae85259d",
                    "mount_point": "/",
                    "mount_options": null
                },
                "partitions": [],
                "used_size": 479555747840,
                "available_size": 0,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/101/"
            }
        ],
        "last_sync": null,
        "bcaches": [],
        "status_name": "Deployed",
        "power_state": "on",
        "pod": null,
        "status_message": "Failed to query node's BMC - Connection timed out while performing power action.  Check BMC configuration and connectivity and try again.",
        "interface_test_status_name": "Unknown",
        "workload_annotations": {},
        "netboot": false,
        "current_commissioning_result_id": 398,
        "numanode_set": [
            {
                "index": 0,
                "memory": 98304,
                "cores": [
                    0,
                    40,
                    1,
                    41,
                    2,
                    42,
                    3,
                    43,
                    4,
                    44,
                    45,
                    5,
                    46,
                    6,
                    47,
                    7,
                    48,
                    8,
                    49,
                    9,
                    10,
                    50,
                    11,
                    51,
                    12,
                    52,
                    13,
                    53,
                    14,
                    54,
                    15,
                    55,
                    16,
                    56,
                    17,
                    57,
                    18,
                    58,
                    19,
                    59
                ],
                "hugepages_set": []
            },
            {
                "index": 1,
                "memory": 100352,
                "cores": [
                    20,
                    60,
                    21,
                    61,
                    22,
                    62,
                    23,
                    63,
                    24,
                    64,
                    25,
                    65,
                    26,
                    66,
                    27,
                    67,
                    28,
                    68,
                    29,
                    69,
                    30,
                    70,
                    31,
                    71,
                    32,
                    72,
                    33,
                    73,
                    34,
                    74,
                    35,
                    75,
                    36,
                    76,
                    37,
                    77,
                    38,
                    78,
                    39,
                    79
                ],
                "hugepages_set": []
            }
        ],
        "disable_ipv4": false,
        "raids": [],
        "fqdn": "node01.maas",
        "description": "node01 bare-metal host",
        "special_filesystems": [],
        "storage": 2480502.915072,
        "sync_interval": null,
        "swap_size": null,
        "other_test_status": -1,
        "owner": "intel",
        "cache_sets": [],
        "current_testing_result_id": 401,
        "architecture": "amd64/generic",
        "other_test_status_name": "Unknown",
        "storage_test_status_name": "Passed",
        "testing_status_name": "Passed",
        "domain": {
            "authoritative": true,
            "ttl": null,
            "id": 0,
            "is_default": true,
            "resource_record_count": 8,
            "name": "maas",
            "resource_uri": "/MAAS/api/2.0/domains/0/"
        },
        "pool": {
            "name": "SHARED",
            "description": "",
            "id": 1,
            "resource_uri": "/MAAS/api/2.0/resourcepool/1/"
        },
        "osystem": "ubuntu",
        "node_type": 0,
        "hostname": "node01",
        "virtualblockdevice_set": [
            {
                "uuid": "24e02618-b16a-49a0-9bbf-86b6bbc890bc",
                "path": "/dev/disk/by-dname/vgroot-lvroot",
                "serial": null,
                "size": 479555747840,
                "partition_table_type": null,
                "block_size": 4096,
                "type": "virtual",
                "system_id": "xca83r",
                "tags": [],
                "used_for": "ext4 formatted filesystem mounted at /",
                "storage_pool": null,
                "name": "vgroot-lvroot",
                "numa_node": null,
                "id_path": null,
                "id": 101,
                "model": null,
                "filesystem": {
                    "fstype": "ext4",
                    "label": "root",
                    "uuid": "c08143d5-b9c9-4853-9113-cb10ae85259d",
                    "mount_point": "/",
                    "mount_options": null
                },
                "partitions": [],
                "used_size": 479555747840,
                "available_size": 0,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/101/"
            }
        ],
        "owner_data": {},
        "node_type_name": "Machine",
        "memory_test_status_name": "Unknown",
        "network_test_status": -1,
        "storage_test_status": 2,
        "virtualmachine_id": null,
        "commissioning_status": 2,
        "distro_series": "jammy",
        "locked": true,
        "physicalblockdevice_set": [
            {
                "firmware_version": "0100",
                "uuid": null,
                "path": "/dev/disk/by-dname/sda",
                "serial": "BTYF832007GQ480BGN",
                "size": 480103981056,
                "partition_table_type": "GPT",
                "block_size": 4096,
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "ssd"
                ],
                "used_for": "GPT partitioned with 2 partitions",
                "storage_pool": null,
                "name": "sda",
                "numa_node": 0,
                "id_path": "/dev/disk/by-id/wwn-0x55cd2e414fd81ab5",
                "id": 36,
                "model": "INTEL SSDSC2KB48",
                "filesystem": null,
                "partitions": [
                    {
                        "uuid": "55f46dc8-c0b1-402b-a189-8a527c335bbc",
                        "size": 536870912,
                        "bootable": true,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sda-part1",
                        "used_for": "fat32 formatted filesystem mounted at /boot/efi",
                        "device_id": 36,
                        "id": 88,
                        "filesystem": {
                            "fstype": "fat32",
                            "label": "efi",
                            "uuid": "e720f90b-ed63-4e7e-9a31-d5a265481205",
                            "mount_point": "/boot/efi",
                            "mount_options": null
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/88"
                    },
                    {
                        "uuid": "97c411c5-03d8-4c84-9ed8-ae415b5599db",
                        "size": 479559942144,
                        "bootable": false,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sda-part2",
                        "used_for": "LVM volume for vgroot",
                        "device_id": 36,
                        "id": 89,
                        "filesystem": {
                            "fstype": "lvm-pv",
                            "label": null,
                            "uuid": "b080d210-ca82-478d-8fea-22c3548aa2a5",
                            "mount_point": null,
                            "mount_options": null
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/89"
                    }
                ],
                "used_size": 480102055936,
                "available_size": 0,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/"
            },
            {
                "firmware_version": "CC26",
                "uuid": null,
                "path": "/dev/disk/by-dname/sdb",
                "serial": "Z4ZAYHSC",
                "size": 2000398934016,
                "partition_table_type": "GPT",
                "block_size": 4096,
                "type": "physical",
                "system_id": "xca83r",
                "tags": [
                    "rotary",
                    "1rpm"
                ],
                "used_for": "GPT partitioned with 1 partition",
                "storage_pool": null,
                "name": "sdb",
                "numa_node": 0,
                "id_path": "/dev/disk/by-id/wwn-0x5000c500b0b65305",
                "id": 37,
                "model": "ST2000DM006-2DM1",
                "filesystem": null,
                "partitions": [
                    {
                        "uuid": "0a22bbfa-04a1-4b88-80f1-1519da666b16",
                        "size": 2000389406720,
                        "bootable": false,
                        "tags": [],
                        "path": "/dev/disk/by-dname/sdb-part1",
                        "used_for": "btrfs formatted filesystem mounted at /var/lib/libvirt",
                        "device_id": 37,
                        "id": 92,
                        "filesystem": {
                            "fstype": "btrfs",
                            "label": "",
                            "uuid": "f98aeed2-16bf-4ccb-a1a4-fb2baf40cb3b",
                            "mount_point": "/var/lib/libvirt",
                            "mount_options": ""
                        },
                        "type": "partition",
                        "system_id": "xca83r",
                        "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/37/partition/92"
                    }
                ],
                "used_size": 2000394649600,
                "available_size": 4194304,
                "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/37/"
            }
        ],
        "next_sync": null,
        "current_installation_result_id": 525,
        "ip_addresses": [
            "10.21.26.1"
        ],
        "network_test_status_name": "Unknown",
        "volume_groups": [
            {
                "system_id": "xca83r",
                "id": 23,
                "__incomplete__": true
            }
        ],
        "cpu_test_status_name": "Unknown",
        "memory_test_status": -1,
        "min_hwe_kernel": "",
        "hardware_uuid": "80dac623-d2e9-e811-906e-000ffee02d5c",
        "boot_disk": {
            "firmware_version": "0100",
            "uuid": null,
            "path": "/dev/disk/by-dname/sda",
            "serial": "BTYF832007GQ480BGN",
            "size": 480103981056,
            "partition_table_type": "GPT",
            "block_size": 4096,
            "type": "physical",
            "system_id": "xca83r",
            "tags": [
                "ssd"
            ],
            "used_for": "GPT partitioned with 2 partitions",
            "storage_pool": null,
            "name": "sda",
            "numa_node": 0,
            "id_path": "/dev/disk/by-id/wwn-0x55cd2e414fd81ab5",
            "id": 36,
            "model": "INTEL SSDSC2KB48",
            "filesystem": null,
            "partitions": [
                {
                    "uuid": "55f46dc8-c0b1-402b-a189-8a527c335bbc",
                    "size": 536870912,
                    "bootable": true,
                    "tags": [],
                    "path": "/dev/disk/by-dname/sda-part1",
                    "used_for": "fat32 formatted filesystem mounted at /boot/efi",
                    "device_id": 36,
                    "id": 88,
                    "filesystem": {
                        "fstype": "fat32",
                        "label": "efi",
                        "uuid": "e720f90b-ed63-4e7e-9a31-d5a265481205",
                        "mount_point": "/boot/efi",
                        "mount_options": null
                    },
                    "type": "partition",
                    "system_id": "xca83r",
                    "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/88"
                },
                {
                    "uuid": "97c411c5-03d8-4c84-9ed8-ae415b5599db",
                    "size": 479559942144,
                    "bootable": false,
                    "tags": [],
                    "path": "/dev/disk/by-dname/sda-part2",
                    "used_for": "LVM volume for vgroot",
                    "device_id": 36,
                    "id": 89,
                    "filesystem": {
                        "fstype": "lvm-pv",
                        "label": null,
                        "uuid": "b080d210-ca82-478d-8fea-22c3548aa2a5",
                        "mount_point": null,
                        "mount_options": null
                    },
                    "type": "partition",
                    "system_id": "xca83r",
                    "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/partition/89"
                }
            ],
            "used_size": 480102055936,
            "available_size": 0,
            "resource_uri": "/MAAS/api/2.0/nodes/xca83r/blockdevices/36/"
        },
        "tag_names": [
            "vm_host"
        ],
        "interface_test_status": -1,
        "resource_uri": "/MAAS/api/2.0/machines/xca83r/"
    }
`
)

func TestUnmarshalMachine(t *testing.T) {
	expected := Machine{}

	err := json.Unmarshal([]byte(input), &expected)
	if err != nil {
		t.Errorf("Failed to unmarshal input: %v", err)
	}
}
