# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import module_pb2 as module__pb2
import plugin_pb2 as plugin__pb2


class ModuleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/module.ModuleService/Register',
                request_serializer=module__pb2.ModuleRegisterRequest.SerializeToString,
                response_deserializer=module__pb2.ModuleRegisterResponse.FromString,
                )
        self.Call = channel.unary_unary(
                '/module.ModuleService/Call',
                request_serializer=plugin__pb2.EndpointRequestMessage.SerializeToString,
                response_deserializer=plugin__pb2.EndpointResponseMessage.FromString,
                )
        self.LoggingStream = channel.unary_stream(
                '/module.ModuleService/LoggingStream',
                request_serializer=plugin__pb2.LoggingArgs.SerializeToString,
                response_deserializer=plugin__pb2.LogMessage.FromString,
                )
        self.RequestToken = channel.unary_unary(
                '/module.ModuleService/RequestToken',
                request_serializer=module__pb2.TokenRequest.SerializeToString,
                response_deserializer=module__pb2.TokenResponse.FromString,
                )
        self.RefreshToken = channel.unary_unary(
                '/module.ModuleService/RefreshToken',
                request_serializer=module__pb2.TokenRefreshRequest.SerializeToString,
                response_deserializer=module__pb2.TokenResponse.FromString,
                )


class ModuleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoggingStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=module__pb2.ModuleRegisterRequest.FromString,
                    response_serializer=module__pb2.ModuleRegisterResponse.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=plugin__pb2.EndpointRequestMessage.FromString,
                    response_serializer=plugin__pb2.EndpointResponseMessage.SerializeToString,
            ),
            'LoggingStream': grpc.unary_stream_rpc_method_handler(
                    servicer.LoggingStream,
                    request_deserializer=plugin__pb2.LoggingArgs.FromString,
                    response_serializer=plugin__pb2.LogMessage.SerializeToString,
            ),
            'RequestToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestToken,
                    request_deserializer=module__pb2.TokenRequest.FromString,
                    response_serializer=module__pb2.TokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=module__pb2.TokenRefreshRequest.FromString,
                    response_serializer=module__pb2.TokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'module.ModuleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModuleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/module.ModuleService/Register',
            module__pb2.ModuleRegisterRequest.SerializeToString,
            module__pb2.ModuleRegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/module.ModuleService/Call',
            plugin__pb2.EndpointRequestMessage.SerializeToString,
            plugin__pb2.EndpointResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoggingStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/module.ModuleService/LoggingStream',
            plugin__pb2.LoggingArgs.SerializeToString,
            plugin__pb2.LogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/module.ModuleService/RequestToken',
            module__pb2.TokenRequest.SerializeToString,
            module__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/module.ModuleService/RefreshToken',
            module__pb2.TokenRefreshRequest.SerializeToString,
            module__pb2.TokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
